# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ebs-csi-controller
#   namespace: kube-system
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::991122344296:role/eks-ebs-csi-driver
# ---